compressionLevel: mixed

enableConstraintsChecks: true

enableGlobalCache: true

enableScripts: false

nodeLinker: node-modules

# Set cool down period for npm packages to 24 hours
# This prevents the installation of npm packages if
# they are updated within the last 24 hours
npmMinimalAgeGate: 1440
# Allow in-house @safe-global packages to bypass the age gate
npmPreapprovedPackages:
  - '@safe-global/*'
